using System.Collections;
using UnityEngine;

public class MoveComponent : MonoBehaviour
{
    Transform playerTransform;
    void Start()
    {
        playerTransform=FindObjectOfType<PlayerController>().transform;
    }
    void OnTriggerEnter(Collider other)
    {
        if (other.gameObject.CompareTag("Player"))
        {
            ObjectSpawner objectS = FindObjectOfType<ObjectSpawner>();
            if (objectS != null)
            {
                objectS.SpawnGround();
                // Zemini ge√ßtikten sonra pasif hale getirme
                //if(playerTransform.transform.position.z<this.gameObject.transform.position.z)
                Debug.Log($"Player spawned");
            }
        }
    }

   
}
